### ISSUE TITLE
Haskell Extension Pack does not work without additional steps

### ISSUE THREAD

**Issue by DaneWeber** [devcontainers-contrib/features#135]
I'm looking to create further PRs for the [Haskell Feature](https://github.com/devcontainers-contrib/features/tree/main/src/haskell), but before I do I want to check that I'm on the right path.

Is editing the `install.sh` and `devcontainer-feature.json` files directly in this repo the right approach? I observed [a conversation about cookie cutter and generating these files](https://github.com/devcontainers-contrib/features/issues/75), but I'm not sure I'm following the vision for the future.

I'm new to Haskell and learning a little bit of it through [Exercism](https://exercism.org/). I want to try it out in a container in VS Code using what appear to be the most popular plug-ins, the [Haskell Extension Pack](https://marketplace.visualstudio.com/items?itemName=mogeko.haskell-extension-pack). Does it fit with the design goals for this repo for me to add steps and change defaults so that the base Haskell Feature supports the following scenario?

1. Open a fresh directory with a simple "Hello World" Haskell program in VS Code.
2. Execute the **Add Dev Container Configuration Files** command
3. Choose **Ubuntu** with the default **jammy** version.
4. Add the **Haskell** Feature listed.
5. Select **Reopen in Container**.
6. Find the "[Haskell Extension Pack](https://marketplace.visualstudio.com/items?itemName=mogeko.haskell-extension-pack)" extension and choose to **Install** it in the Dev Container.
7. Open the `HelloWorld.hs` file and benefit from the extensions without further action needed.

At present, when I complete the steps above, I see a prompt to download `hls-1.8.0.0` and also that `hlint` cannot be found.

<img width="464" alt="image" src="https://user-images.githubusercontent.com/5520906/204391622-c7855412-5785-43bc-96fd-34942f3f3b85.png">

Agreeing to install HLS results in further errors because of version mismatches.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/5520906/204392033-1fe9f820-af97-4a37-8c1a-58deb014c24a.png">

I didn't save my steps, but I got everything working previously and believe I can set up the Haskell Feature to run these extensions out of the box.

@danielbraun89, before I do so: is that a desirable set of changes? If it affects your answer, I'm also planning to do something similar for additional languages that have Exercism tracks (such as Clojure, Elixir, and Scala).

**Comment by DaneWeber** [comment]
Thanks, I'll take a look. I will say this, though: I wasn't looking to add docs but to modify the Feature so that the VS Code extensions work out of the box.

I'm really interested in the Features because I've found myself taking two or three Dockerfiles and copy-pasting from them to create the Dockerfile I want. Even in my current use-case, however, I'd like to create a custom Dev Container for running VS Code that has git and my Exercism CLI installed and configured (once for all languages/tracks) and then adds a specific language Feature depending on which track I open.

I'll see if I can just open a PR to make clear what I'm thinking since it at least sounds like my effort won't be wasted.

**Comment by jcbhmr** [comment]
> I wasn't looking to add docs but to modify the Feature so that the VS Code extensions work out of the box.

@DaneWeber Sorry for the misunderstanding on my part 😬. That sounds like a good idea, though 👍!

**Comment by DaneWeber** [comment]
@jcbhmr or @danielbraun89 -- Do either of you know how to preserve the build logs when building a devcontainer? I'm just building them in VS Code and the logs for the Feature installation get bundled up into a single line that doesn't help me figure out what might've gone wrong or even what the script echoed out.
<img width="516" alt="image" src="https://user-images.githubusercontent.com/5520906/205398439-5a60e6fd-5427-43c9-bc30-1492a4f5a0e2.png">

**Comment by jcbhmr** [comment]
It doesn't seem like the CLI respects `TERM=dumb`, `2> stderr.log` or `> stdout.log`. Even with all those, it still outputs a mess. But! The good thing is that it doesn't "clear the screen" like the TTY terminal does. Thus, this works:

```sh
devcontainer features test -f jest 2> stderr.log
```

It shows something like this:

```
[[1m[38;2;99;143;79m1 ms[39m[22m] @devcontainers/cli 0.25.2. Node.js v16.18.1. linux 5.4.0-1094-azure x64.
[[1m[38;2;99;143;79m484 ms[39m[22m] Start: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-codespace/container-features/0.25.2-1670050215072 --build-arg _DEV_CONTAINERS_BASE_IMAGE=ubuntu:focal --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-1670050214548-6a9d9fccd3ecec4aec72582743637f90-features -f /tmp/devcontainercli-codespace/container-features/0.25.2-1670050215072/Dockerfile.extended /tmp/devcontainercli-codespace/empty-folder
[1A[1B[0G[?25l[+] Building 0.0s (0/0)                                                         
[?25h[1A[0G[?25l[+] Building 0.1s (1/2)                                                         
[34m => [internal] load build definition from Dockerfile.extended              0.1s
[0m[34m => => transferring dockerfile: 998B                                       0.0s
[0m => [internal] load .dockerignore                                          0.1s
[34m => => transferring context: 2B                                            0.0s
[0m[?25h[1A[1A[1A[1A[1A[0G[?25l[+] Building 0.2s (2/2)                                                         
[34m => [internal] load build definition from Dockerfile.extended              0.1s
[0m[34m => => transferring dockerfile: 998B                                       0.0s
[0m[34m => [internal] load .dockerignore                                          0.1s
[0m[34m => => transferring context: 2B                                            0.0s
[0m[?25h[1A[1A[1A[1A[1A[0G[?25l[+] Building 0.4s (2/3)                                                         
[34m => [internal] load build definition from Dockerfile.extended              0.1s
[0m[34m => => transferring dockerfile: 998B                                       0.0s
[0m[34m => [internal] load .dockerignore                                          0.1s
[0m[34m => => transferring context: 2B                                            0.0s
[0m => resolve image config for docker.io/docker/dockerfile:1.4               0.1s                  
```

Which, yes, is a mess; but it DOES contain all the info! It's just messed up with some blue coloring prefix characters.
