### ISSUE TITLE
Consider deleting old branches

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/features#162]
![image](https://user-images.githubusercontent.com/61068799/205123011-349fea27-a8eb-4bb3-8981-f7f1e044a681.png)

I think @danielbraun89 is the only one with the power to do this.

**Comment by danielbraun89** [comment]
I have deleted manually something like 30 branched, but some have this "Protected" badge on them, I have yet to understand how they got this status 
![image](https://user-images.githubusercontent.com/17760492/205439071-3aa750fd-8b16-47c0-8d3d-c07b9981b19f.png)

**Comment by jcbhmr** [comment]
@danielbraun89 it appears that those branches are protected.

![image](https://user-images.githubusercontent.com/61068799/205460970-27244d53-7f42-4918-a68f-319031ba3000.png)

If you check in the Settings tab under the Branches option on the left side, you should get a menu with a bunch of options about branch protection.

![image](https://user-images.githubusercontent.com/61068799/205460995-211fb98f-cbdc-4e41-ad36-c949ddddbb7d.png)

Are there any rules in there? 🤔

**Comment by jcbhmr** [comment]
Closing this since it seems to be low priority and cluttering the issue tracker
