### ISSUE TITLE
pipenv option "version" should be type string instead of boolean?

### ISSUE THREAD

**Issue by djbrown** [devcontainers-contrib/features#184]
https://github.com/devcontainers-contrib/features/blob/fd663da53b695a8ed7fae18ed6fdff94fdb20db0/src/pipenv/devcontainer-feature.json#L13

**Comment by danielbraun89** [comment]
damn I cant believe this went unnoticed , I guess no validation from devcontainre cli on these "types" , fixed in 488b72ccecfbfa676fde2be5863b2aeb6a773080
