### ISSUE TITLE
Github actions has max matrix size of 256 which will soon be a limiting factor

### ISSUE THREAD

**Issue by danielbraun89** [devcontainers-contrib/features#201]
Currently each feature test is being run in its own action runner which is limited by github to  256 (https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs)

Possible solution is to run the tests in a single runner

Must ensure:
- it is highly parallel in order to decrease run time
- can print logs of all tests in a structured and easily read order

**Comment by jcbhmr** [comment]
> it is highly parallel in order to decrease run time

A comment: I think this should be _secondary_. First up on the docket is to get it _working_.

---

Does `devcontainer features test` work with the current repo layout? That would seem like the ideal way to go about this. Maybe with a loop that does each one individually?
