### ISSUE TITLE
apt-packages v.s. apt-get-packages

### ISSUE THREAD

**Issue by eitsupi** [devcontainers-contrib/features#206]
Hi, @danielbraun89.
You have recently released `apt-get-packages` in ccd4c1f71272d86be790f14d2562dc54e9af25ab, but there is already a functionality equivalent to this that has been released.

https://github.com/rocker-org/devcontainer-features/blob/main/src/apt-packages

Were you aware of this?
Wouldn't it be better to manage one jointly than two similar ones?

I have run into this same thing in the past.
devcontainers/spec#155

**Comment by danielbraun89** [comment]
@eitsupi  
I was not at all aware about the apt-packages feature😅 (my apt-get-packages was part of a larger attempt to have more generic features as per #172  (for example I have also added[ npm-package](https://github.com/devcontainers-contrib/features/tree/main/src/npm-package) , [pipx-package](https://github.com/devcontainers-contrib/features/tree/main/src/pipx-package)  and [asdf-package](https://github.com/devcontainers-contrib/features/tree/main/src/asdf-package))

I agree it would be better to be maintained jointly
As I see the feature has not yet been "grabbed" by github ill just delete the [feature package](https://github.com/devcontainers-contrib/features/pkgs/container/features%2Fapt-get-packages), If we are lucky it will be enough to prevent from the headache of deprecating it later 😄 

On another note - considering that a minor feature like k9s has already [1](https://github.com/dhoeric/features/tree/main/src/k9s) [2](https://github.com/natescherer/devcontainers-custom-features) and [3](https://github.com/rio/features/tree/main/src/k9s) implementations -and that this devcontainer feature framework is really still in its infancy, it is inevitable that _someone_ _somewhen_ will reimplement this yet again. but one step at a time!

**Comment by danielbraun89** [comment]
@eitsupi  
I was not at all aware about the apt-packages feature😅 (my apt-get-packages was part of a larger attempt to have more generic features as per #172  (for example I have also added[ npm-package](https://github.com/devcontainers-contrib/features/tree/main/src/npm-package) , [pipx-package](https://github.com/devcontainers-contrib/features/tree/main/src/pipx-package)  and [asdf-package](https://github.com/devcontainers-contrib/features/tree/main/src/asdf-package))

I fully agree it would be better to be maintained jointly!
As I see that my feature has not yet been "grabbed" by github ill just delete the [feature package](https://github.com/devcontainers-contrib/features/pkgs/container/features%2Fapt-get-packages), If we are lucky it will be enough to prevent from the headache of deprecating it later  

On another note - considering that a minor feature like k9s has already [1](https://github.com/dhoeric/features/tree/main/src/k9s) [2](https://github.com/natescherer/devcontainers-custom-features) and [3](https://github.com/rio/features/tree/main/src/k9s) implementations -and that this devcontainer feature framework is really still in its infancy, it is inevitable that _someone_ _somewhen_ will reimplement this yet again. but one step at a time!

**Comment by eitsupi** [comment]
Thanks for your quick response!

This is a really basic feature that I had hoped would be implemented in `devcontainers/features` (devcontainers/features#67) but no progress was made so I published it from rocker-org (since it is useful in combination with other rocker-org' Features).
Since common-utils version2 now supports not only apt but also dnf and apk, I expect that perhaps in the future more generic Feature will be implemented in `devcontainers/features`.

> As I see that my feature has not yet been "grabbed" by github ill just delete the [feature package](https://github.com/devcontainers-contrib/features/pkgs/container/features%2Fapt-get-packages), If we are lucky it will be enough to prevent from the headache of deprecating it later

Since which Features are published is recorded as metadata as https://github.com/devcontainers-contrib/features/pkgs/container/features, deleting only the Feature is insufficient.
We must remove the Feature from in the `src/` directory and then run the publish action again to update the metadata.
(See devcontainers/spec#155)

> On another note - considering that a minor feature like k9s has already [1](https://github.com/dhoeric/features/tree/main/src/k9s?rgh-link-date=2022-12-17T21%3A20%3A20Z) [2](https://github.com/natescherer/devcontainers-custom-features) and [3](https://github.com/rio/features/tree/main/src/k9s?rgh-link-date=2022-12-17T21%3A20%3A20Z) implementations -and that this devcontainer feature framework is really still in its infancy, it is inevitable that _someone_ _somewhen_ will reimplement this yet again.

No doubt.

**Comment by danielbraun89** [comment]
done in 006e18efa8d69a0e0097ada514e11449bfcd0ce6

**Comment by eitsupi** [comment]
Thanks!
