### ISSUE TITLE
angular-cli feature breaks in conjunction with node feature

### ISSUE THREAD

**Issue by natb1** [devcontainers-contrib/features#211]
Hello,

When:
- using both angular-cli and node features
- if setting version of the node feature

The angular-cli script will run first and run its own nvm install script. Then, the node feature will run and update the default alias of node. This makes the installed angular-cli inaccessible in the container (by default).

Related/same issue: the angular-cli overlooks nvm installed node regardless of whether a the node feature was used for installation. Presumably because it's [not using an interactive shell](https://github.com/devcontainers-contrib/features/blob/main/src/angular-cli/install.sh#L39) to check for node.

**Comment by natb1** [comment]
For anybody having this issue, my workaround is to install nvm/node and angular cli using a Dockerfile.

**Comment by danielbraun89** [comment]
fixed in  00ec5c281f15c063fc00259aca89c32dc0842d4b
