### ISSUE TITLE
NOTICE: v1.2 of `devcontainers/action` will now validate `devcontainer-feature.json` schema

### ISSUE THREAD

**Issue by joshspicer** [devcontainers-contrib/features#219]
Wanted to give you guys a heads up that i've enabled schema validation in the action, which will fail the publish if any `devcontainer-feature.json` files do not follow the [published schema](https://github.com/devcontainers/spec/blob/main/schemas/devContainerFeature.schema.json) (typos etc..)

I am not if this will be an issue for your repo, but I suspect with the volume this repo sees, there will be at least a few typos that may block publishing.

If you'd prefer to disable and handle this incrementally, i've added an option to set theses errors as warnings here: https://github.com/devcontainers/action/blob/main/action.yml#L14

**Comment by danielbraun89** [comment]
thanks! 
Indeed we had at least one feature fail that validation so far ("boolean" option instead of "string" , fixed in #a7ced050e74f7ca1d460af6734886e11813005e4 )

**Comment by danielbraun89** [comment]
full release has passed #222
