### ISSUE TITLE
Add a requirements-checker feature

### ISSUE THREAD

**Issue by danielbraun89** [devcontainers-contrib/features#243]
Some hard dependencies are usually hard to convery in feature description
for example Glibc requirements, distro requirements (debian vs redhat)  

This feature should simple warn/exit (flag) when user tries to run it on incompatible base container

**Comment by jcbhmr** [comment]
I think this is similar to the idea proposed in the official devcontainers/features org in this issue: https://github.com/devcontainers/spec/issues/109#issuecomment-1275258914

> What I currently do:
> ```sh
> if ! type python3 >/dev/null 2>&1; then
>   echo "ERROR: Use a base image with python3 installed, add it to your Dockerfile or use a python feature like https://github.com/devcontainers/features/tree/main/src/python"
>   exit 1
> fi

Just drawing a similarity; this isn't really a criticism or a suggestion, just an observation.
