### ISSUE TITLE
What is featmake?

### ISSUE THREAD

**Issue by eitsupi** [devcontainers-contrib/features#246]
Some Features seem to install a binary called featmake, but the source code for this does not appear to be publicly available.

https://github.com/devcontainers-contrib/features/blob/b30385c20e416d66bae07e780f3cc157e04bc35d/src/act-asdf/dependencies.sh#L20

Installing binaries of unknown origin may be unwelcome.

**Comment by jcbhmr** [comment]
I think this is part of @danielbraun89's fancy new CLI that does some feature magic. I'm not personally on board, but it seems like this is the direction he's taking the project. 🤷‍♂️

Regarding random binaries, yeah I think a link or something would be a good idea. The docs also need to be improved big time for this new direction too, both in this repo and in the CLI repo. @danielbraun89 I can help with that 😉📝

Regarding the public/private I wholeheartedly agree. I can find the spot that hosts the asset: https://github.com/devcontainers-contrib/cli/releases, but I can't really find out what generated it... 🤔

**Comment by danielbraun89** [comment]
its a bunch of .sh files which uses [oras](https://github.com/oras-project/oras) to download and unpackage a feature package, set environment variable from its declared defaults, and then runs  the features `install.sh` . I compiled the shell files using [sch](https://github.com/neurobin/shc) as a way of packaging them a single file without introducing another requirements( `unzip`)  beyond `curl` and `oras` . In hindsight it doesnt add enough value to warrant it Ill just combine them all into a single merged .sh file and live with that 😄

**Comment by danielbraun89** [comment]
source code here  https://github.com/devcontainers-contrib/cli/tree/main/resources/featmake

**Comment by danielbraun89** [comment]
from version 0.0.16 and up featmake is now not a binary but a raw shell script, you can open it with any text editor

**Comment by jarrodcolburn** [comment]
For anyone looking like I was, the script mentioned above [`merged_featmake.sh`](https://github.com/devcontainers-contrib/cli/blob/main/resources/featmake/merged_featmake.sh) is now just [`featmake.sh`](https://github.com/devcontainers-contrib/cli/blob/main/resources/featmake/featmake.sh) after (commit 3333faf)

**Comment by jarrodcolburn** [comment]
@danielbraun89 @jcbhmr 
### From what I can tell `featmake` tries to make `features` more modular, a worthy DRY goal! But irnoically, I'm worried it is repetitive of efforts. 

Both CLIs...
* [devcontainers/cli](https://github.com/devcontainers/cli) 
* [decvontainers-contrib/cli](https://github.com/devcontainers-contrib/cli) 

...parse variables and pass/begin initialization (ex: `install.sh`).*

`decvontainers-contrib/cli`, python, runs inside the container, while `devcontainers/cli`, javascript, has access to docker outside the container and many more features.

**So why the duplication of efforts? Has anyone spoken to the maintainers of `devcontainers/cli` to see if they can modularize and extract the functionality we want to use for modularity and reused functionality?**
---------

A quick recap for those who don't know what `featmake` does. An exmaple...

If two separate features exists, A and B, such that...
- A. installs `Homebrew` 
- B. installs `NeoVim` via `Homebrew`

...`feature B` reuses `feature A` by doing the following step...
From with Feature B's `docker/devcontainer`....
1. download `oras`
2. use `oras` to download and extract `feature A`
3. `featmake` parses `json` and becins initialization of `feature A`.

---------

All these steps seem to be implemented within the `devcontainers/cli` already.
