### ISSUE TITLE
ZSH Plugins are installed incorrectly

### ISSUE THREAD

**Issue by nandordudas** [devcontainers-contrib/features#247]
https://github.com/devcontainers-contrib/features/blob/b30385c20e416d66bae07e780f3cc157e04bc35d/src/zsh-plugins/install.sh#L21

Please consider the using of following script. I had replaced the whole code - I hope it helps 🤞 -, but the main reason is the space separated list.

### Short fix

```diff
- plugins=( "${OMZSH_PLUGINS}" )
+ IFS=' ' read -ra plugins <<< "${OMZSH_PLUGINS}"
```

### Long fix - [shellcheck]

```bash
#!/usr/bin/env bash

PLUGINS=${PLUGINS:-""}
OMZSH_PLUGINS=${OMZPLUGINS:-""}

install_zsh_plugins() {
  local -a plugins
  local zsh_custom="$HOME/.oh-my-zsh/custom"

  # Read space separated string into list
  IFS=' ' read -ra plugins <<< "$1"

  # Make sure the working directory exists
  mkdir -p "${zsh_custom}/plugins"

  # Use working directory
  pushd "${_}" >/dev/null 2>&1 || exit
  for plugin in "${plugins[@]}"; do
    echo "$plugin"
  done
  popd >/dev/null 2>&1 || exit

  # Activate zsh plugins
  sed -ie "s/plugins=.*/plugins=(git $PLUGINS)/g" "${ZSH_CONFIG}"
}

main() {
  install_zsh_plugins "${OMZSH_PLUGINS}"
}

main
```

```json
{
  "features": {
    "ghcr.io/devcontainers-contrib/features/zsh-plugins:0": {
      "plugins": "git node F-Sy-H zsh-autocomplete",
      "omzPlugins": "https://github.com/z-shell/F-Sy-H https://github.com/marlonrichert/zsh-autocomplete"
    }
  }
}
```

`$_` uses the most recently used argument
`>/dev/null 2>&1` redirects the output to null

I love this feature and I want to use it, but it's not working now.

Thanks!

[shellcheck]: https://www.shellcheck.net/

**Comment by nandordudas** [comment]
And maybe an array would be friendlier in options - 😅.

```json
{
  "features": {
    "ghcr.io/devcontainers-contrib/features/zsh-plugins:0": {
      "plugins": "git F-Sy-H zsh-autocomplete",
      "omzPlugins": [
        "https://github.com/z-shell/F-Sy-H",
        "https://github.com/marlonrichert/zsh-autocomplete"
      ]
    }
  }
}
```

**Comment by danielbraun89** [comment]
@nandordudas  Thanks for finding this!  

Although I'm not the original contributor for this feature and have minor proficiency with zsh, I saw that your short fix did not break the earlier test so I see no reason not to merge it 

I have opened a PR for it here #248, and added your params configuration as [a new test scenario](https://github.com/devcontainers-contrib/features/pull/248/files#diff-30fbc72a149a5c9fe8f45f4dd2c345289204e08306b818dc18f00f8ccf820820)

@gund do you see a problem with merging the longer version?

**Comment by gund** [comment]
The longer version seems fine, although I would probably keep the username option as most of the devcontainer features use it, so it's probably a convention to have it.

Otherwise looks fine if it works👍

**Comment by ms-vamp** [comment]
i am having an issue running this script in a Dockerfile:

```sh
RUN USERNAME=root \
    PLUGINS='zsh-nvm zsh-autosuggestions' \
    OMZSH_PLUGINS='https://github.com/lukechilds/zsh-nvm.git https://github.com/zsh-users/zsh-autosuggestions' \
    /bin/bash \
    -c "$(curl -fsSL https://raw.githubusercontent.com/devcontainers-contrib/features/main/src/zsh-plugins/install.sh)"
```

when i enter the container i get this error

```sh
[oh-my-zsh] plugin 'zsh-nvm' not found
[oh-my-zsh] plugin 'zsh-autosuggestions' not found
```

looking in `/root/.oh-my-zsh/plugins/` dir it shows none of the repos were cloned.

it is, however, correctly adding to `/root/.zshrc` plugins section

```sh
plugins=(git zsh-nvm zsh-autosuggestions)
```

**Comment by ms-vamp** [comment]
here is the full dockerfile for reference. it is using the base ubunu devcontainer image 

```sh
# hack to force always using AMD64 (will work on WSL2/macOS)
FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/base:ubuntu

USER root

WORKDIR /install

RUN USERNAME=root \
    PLUGINS='zsh-nvm zsh-autosuggestions' \
    OMZSH_PLUGINS='https://github.com/lukechilds/zsh-nvm.git https://github.com/zsh-users/zsh-autosuggestions' \
    /bin/bash \
    -c "$(curl -fsSL https://raw.githubusercontent.com/devcontainers-contrib/features/main/src/zsh-plugins/install.sh)"
```

**Comment by gund** [comment]
It's hard to guess what might be the issue but you could try to normalize git (remove trailing `.git` extensions) urls and see if it fixes the issue:
```
OMZSH_PLUGINS='https://github.com/lukechilds/zsh-nvm https://github.com/zsh-users/zsh-autosuggestions'
```

Also worth looking at the build logs to try and spot any error messages there.
And the final thing to try is to copy the install script locally and add a few logs like dump the value of the `plugins` variable to see  if they are properly split into an array and maybe a few more logs in the loop.

**Comment by ms-vamp** [comment]
> It's hard to guess what might be the issue but you could try to normalize git (remove trailing `.git` extensions) urls and see if it fixes the issue:
> 
> ```
> OMZSH_PLUGINS='https://github.com/lukechilds/zsh-nvm https://github.com/zsh-users/zsh-autosuggestions'
> ```
> 
> Also worth looking at the build logs to try and spot any error messages there. And the final thing to try is to copy the install script locally and add a few logs like dump the value of the `plugins` variable to see if they are properly split into an array and maybe a few more logs in the loop.

i sorted it out. user error.

i read the script source and saw the var `OMZSH_PLUGINS` so i thought thats what needed to be set. that is the var used internally but it actually defaults to `OMZPLUGINS`. once i set that it worked fine

```sh
OMZSH_PLUGINS=${OMZPLUGINS:-""}
```

also i am curious now looking at it do we need `USERNAME` or can we use `ZSH` env var to discover the `.zshrc` path?

**Comment by gund** [comment]
Devcontainers already provides default user in `$_REMOTE_USER` and it's used by default:
https://github.com/devcontainers-contrib/features/blob/c5b9034c540ed61967fa0eaba8f57b24c0a4f311/src/zsh-plugins/install.sh#L5

But if you are running this in your custom build then you should provide the user as there is no default.
