### ISSUE TITLE
Add/Move pnpm

### ISSUE THREAD

**Issue by NicoVIII** [devcontainers-contrib/features#265]
For now pnpm resides in it's own lonely repository but is already based on templates used by this repository.
I think it would be wise to move this into this repo.
https://github.com/NicoVIII/devcontainer-features/tree/main/src/pnpm

Would that be fine with you? I think pnpm is so simple to install that you can simply generate the code for that with your tooling and then we could change the referenced package on the devcontainers side via PR to the one provided by this repository.

**Comment by danielbraun89** [comment]
@NicoVIII sure, no problem!  Thanks for introducing me to pnpm its very interesting! 

It was easy enough to generate a feature definition and the feature itself , 
now in this PR waiting for your green light #276
