### ISSUE TITLE
Interested in joining the slack channel for devcontainers?

### ISSUE THREAD

**Issue by craiglpeters** [devcontainers-contrib/features#269]
@danielbraun89 Thank you for all the great contributions! We'd love to have you join our community. Feel free to let us know how to reach you here: https://github.com/devcontainers/community/discussions/3

**Comment by bamurtaugh** [comment]
Hey @danielbraun89! I'm a PM on the VS Code team and co-maintainer of the dev container spec: https://github.com/devcontainers/spec. This org is great to see - it's fantastic seeing your contributions and passion for dev containers. 

It'd be awesome to connect and learn more about your feedback and usage, which can really help us shape the future of dev containers. If you're interested in joining our Slack or chatting further, please feel free to comment on the issue @craiglpeters linked, and/or just let us know here. Thank you!

**Comment by danielbraun89** [comment]
thanks for pinging me about this, sounds awesom! I will comment on the issue

**Comment by bamurtaugh** [comment]
Awesome, thank you so much! You should get added soon 😄.
