### ISSUE TITLE
Update README description, repo description, and repo tags

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/features#286]
Given that this org has expanded into other areas that also have Docker-related things, I think the emoji 🐳 should be changed to something like a toolbox 🧰

While we're at it, why not update the description to include a tag to the official @devcontainers org?

Here's my proposal:

**Readme and repo description:** \
🧰 Feature addons for @devcontainers

**Repo tags:** \
devcontainers devcontainer-feature

/assign @jcbhmr to change the readme

I will need @danielbraun89 to actually edit the repo's description and tags

Also, if we ever get a GitHub Pages site we should add a website link too. And we should also add a social image too.

**Comment by gromag** [comment]
I'm trying to find out more about act-asdf but the automatically generated documentation is quite poor. I think it would be helpful if you could expand the documentation for newcomers.

**Comment by jcbhmr** [comment]
@gromag You're absolutely right that documentation isn't very _there_ at all. @danielbraun89 recently has transitioned (a few weeks ago) to a more complex system of creating features, and the documentation that I wrote before is now sorely out-of-date.

Here's a possible future readme:

![image](https://user-images.githubusercontent.com/61068799/215211164-aab9fea6-6000-4b86-929c-1cab42bf3e3a.png)
![image](https://user-images.githubusercontent.com/61068799/215211513-49b17f50-c080-46e4-83f7-9a73c6c04592.png)


And maybe we'll get some GitHub Pages website spun up to serve more in depth documentation about each feature! Follow progress on https://github.com/devcontainers-contrib/features/pull/291 and more discussion in https://github.com/devcontainers-contrib/features/discussions/290 for more talk about current pitfalls and friction points.

**Comment by jcbhmr** [comment]
@gromag If you have any ideas for stuff that you want to see on a theoretical HTML GitHub Pages site, tell me! I want to know! So far my only idea for improvement is too add a link to create a new GitHub Issue.

You can track the future `[id].php` file that generates all this stuff here: https://github.com/jcbhmr/devcontainers-contrib-features/blob/main/docs/pages/[id].php

**Comment by jcbhmr** [comment]
📬 @danielbraun89 Pls add tags/update description of repo:

![image](https://user-images.githubusercontent.com/61068799/216699411-6353bf83-6f70-437c-b306-a945ff4d74f0.png)

**Comment by jcbhmr** [comment]
Doubtful this will happen. Closing to focus on actual bugs.
