### ISSUE TITLE
Use camelCase for options

### ISSUE THREAD

**Issue by eitsupi** [devcontainers-contrib/features#3]
I'm wondering if you should use snake_case here.
Note that all devcontainers's features use camelCase.

https://github.com/devcontainers-contrib/features/blob/a1a3d1c5af8d63b58f15562909e5285172920792/src/pulumi/devcontainer-feature.json#L16

**Comment by joshspicer** [comment]
+1.  Not a hard requirement, but we're trying to follow JSON conventions here and use camelCase for user simplicity. 

Note that in your in your install.sh you'll need to expect the upper case "smashed together" `BASHCOMPLETION` if you do make this change :)

**Comment by danielbraun89** [comment]
Got it! thanks for the heads-up!
