### ISSUE TITLE
Communication frustrations

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/features#316]
_Original title: Turn on GitHub Pages on devcontainers-contrib/templates_

Hello! Sorry for creating an entire issue for what basically amounts to an annoying ping... But I don't know how else to reach you @danielbraun89. https://github.com/devcontainers-contrib/templates/pull/15 needs an action item: enable GitHub Pages from Actions.

If I had to guess, you've turned down your notifications settings on GitHub and/or aren't "Watching" the devcontainers-contrib/templates repo.

This is becoming a recurring theme for my interactions with you. I guess I'll just be blunt and state it outright: communication kinda sucks right now.
- https://github.com/devcontainers-contrib/.github/pull/7 has been open since before Christmas with no interaction
- https://github.com/devcontainers-contrib/templates/pull/15 has been waiting for review and interaction for 2 weeks
- https://github.com/devcontainers-contrib/features/discussions/293
- https://github.com/devcontainers-contrib/features/discussions/290
- https://github.com/devcontainers-contrib/features/discussions/209
- https://github.com/devcontainers-contrib/templates/pull/13
- One-way Gitter conversations

If there's something I can do to make your life easier or to streamline this procces, I'd love to know! 💌 If you're overworked or have picked up another project, that's **great**! Just pretty please **delegate or transfer some power and control to someone else to fill the void**. 🙏 Right now issues and PRs go a while without anything happening. It kinda drains my motivation when I don't get feedback and it feels like I'm doing stuff for nothing.

And considering the popularity of these features (18k+ on Poetry alone, top downloaded one) I think this is a pretty good sized project that warrants some ❤

**Comment by danielbraun89** [comment]
Hi I'm sorry you feel I'm not communicative enough, you are right.  but sadly I cannot invest more time that I already am and not intending adding collaborators at this time.

I would suggest take things with more proportions tho. This repo was meant to be easy and lighthearted 🤷  There is no commercial product on the line here... No deadlines... No urgency...  

Yes, It may take me few weeks to answer at times. But unless its a user breaking bug, so what? Move on to other projects and come back later?

Im sorry but I have no solutions for this at this time... 😞

**Comment by jcbhmr** [comment]
/re @danielbraun89 

> I cannot invest more time that I already am and not intending adding collaborators at this time.

That's OK! 👍

I anticipated this being what was going on, but was holding out hope in case it wasn't.

> I would suggest take things with more proportions tho. I aim this repo to be a nice cute side project, easy and lighthearted 🤷 There is no commercial product on the line here... No deadlines... No urgency...

You're right! Absolutely right. I just think that creating an organization named "devcontainers-contrib" (as opposed to danielbraun89/devcontainer-features or similar) implies an _organization_ (or aspiring organization) level of _official-ness_ that I assumed was intended. Obviously I was wrong. 🤷‍♂️

Adding this sort of goal to the Charter document (in fact, rewriting the charter document based on this new information) would be good. I'll get ChatGPT to do it. 😉 That and maybe tweak the contributing guide or something to put a notice about the intended scope and "no urgency" approach.

Given this new informative development, I'll try to temper my expectations a bit next time I post something.

---

P.S. devcontainers-contrib/templates still needs GitHub Pages to be set to "from github actions" to work with the CI script. https://github.com/devcontainers-contrib/templates/issues/18

**Comment by jcbhmr** [comment]
See https://github.com/devcontainers-contrib/.github/pull/10 for updated charter/scope document
