### ISSUE TITLE
Homebrew errors

### ISSUE THREAD

**Issue by jarrodcolburn** [devcontainers-contrib/features#327]
`homebrew` package feature is long time. I think due to not using sudo? (so is it being installed as a user?)
I'm getting hung for a long time on error message that says 
```shell
 => => # Error: Need to download https://formulae.brew.sh/api/formula.jws.json 
 => => # but cannot as root! Run `brew update` without `sudo` first then try ag
 => => # ain.                                                                  
 => => # +++ brew --prefix                                                     
 => => # ++ git -C /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/ho
 => => # mebrew-core fetch --unshallow 
```
This is effecting features that rely on homebrew. Specifically for me, [neovim-homebrew](https://github.com/devcontainers-contrib/features/tree/main/src/neovim-homebrew) failed installation.

**Comment by danielbraun89** [comment]
This was a truely severe bug, during homebrew 4 the default behavior changed and packages could no longer get installed using root. It has rendered all homebrew based features broken.
The fix was to install with the remote user.
