### ISSUE TITLE
neovim install version outdated

### ISSUE THREAD

**Issue by jarrodcolburn** [devcontainers-contrib/features#328]
Problem:
Old ersion `0.6.1` of neovim is installed through `neovim-apt-get` feature installation, although neovim is up to `0.8.3`.

Why:
Because Neovim has been added to a "Personal Package Archive" (PPA), as per their website
```bash
# sudo apt-get install software-properties-common
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt-get update
sudo apt-get install neovim
```

**Comment by danielbraun89** [comment]
Good catch. I will have to add the ability to use PPA in apt-get package feature. I will keep this issue open as a reference for this feature.

**Comment by jarrodcolburn** [comment]
I may open a ticket on NeoVim's GitHub and see if they'll integrate the feature themselves. They actually have an amazing distribution set not just for apt, but also.. rpm, app image, flat pack.... https://github.com/neovim/neovim/wiki/Installing-Neovim
