### ISSUE TITLE
Regenerate features using new dcontainer cli program

### ISSUE THREAD

**Issue by danielbraun89** [devcontainers-contrib/features#334]
DContainer is the new cli program (https://github.com/devcontainers-contrib/cli) for installing features
It replaces the old "featmake.sh" script

**Comment by dsturnbull** [comment]
I'm unable to install contrib features specifically for v 2.0.8. Rolling back to v 2.0.7 is required. There's no user-visible error for you unfortunately.

```
 > [dev_containers_target_stage 7/8] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=pylint_6,target=/tmp/build-features-src/pylint_6     cp -ar /tmp/build-features-src/pylint_6 /tmp/build-features/  && chmod -R 0700 /tmp/build-features/pylint_6  && cd /tmp/build-features/pylint_6  && chmod +x ./devcontainer-features-install.sh  && 
[2023-03-14T02:46:55.217Z] ./devcontainer-features-install.sh  && rm -rf /tmp/build-features/pylint_6:
#0 0.130 ===========================================================================
#0 0.130 Feature       : Pylint (via pipx)
#0 0.130 Description   : Pylint is a static code analyser for Python 2 or 3.
#0 0.130 Id            : ghcr.io/devcontainers-contrib/features/pylint
#0 0.130 Version       : 2.0.8
#0 0.130 Documentation : http://github.com/devcontainers-contrib/features/tree/main/src/pylint
#0 0.130 Options       :
#0 0.130     VERSION="latest"
#0 0.130 ===========================================================================
#0 7.658 dcontainer: OK
#0 8.626 ERROR: Feature "Pylint (via pipx)" (ghcr.io/devcontainers-contrib/features/pylint) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/pylint for help troubleshooting this error.
------
[2023-03-14T02:46:55.217Z] ERROR: failed to solve: executor failed running [/bin/sh -c cp -ar /tmp/build-features-src/pylint_6 /tmp/build-features/  && chmod -R 0700 /tmp/build-features/pylint_6  && cd /tmp/build-features/pylint_6  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/build-features/pylint_6]: exit code: 127
```

Probably the standout is `exit code: 127`

Please redirect if this comment should become an issue or whateve.r

**Comment by danielbraun89** [comment]
> I'm unable to install contrib features specifically for v 2.0.8. Rolling back to v 2.0.7 is required. There's no user-visible error for you unfortunately.
> 
> ```
>  > [dev_containers_target_stage 7/8] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=pylint_6,target=/tmp/build-features-src/pylint_6     cp -ar /tmp/build-features-src/pylint_6 /tmp/build-features/  && chmod -R 0700 /tmp/build-features/pylint_6  && cd /tmp/build-features/pylint_6  && chmod +x ./devcontainer-features-install.sh  && 
> [2023-03-14T02:46:55.217Z] ./devcontainer-features-install.sh  && rm -rf /tmp/build-features/pylint_6:
> #0 0.130 ===========================================================================
> #0 0.130 Feature       : Pylint (via pipx)
> #0 0.130 Description   : Pylint is a static code analyser for Python 2 or 3.
> #0 0.130 Id            : ghcr.io/devcontainers-contrib/features/pylint
> #0 0.130 Version       : 2.0.8
> #0 0.130 Documentation : http://github.com/devcontainers-contrib/features/tree/main/src/pylint
> #0 0.130 Options       :
> #0 0.130     VERSION="latest"
> #0 0.130 ===========================================================================
> #0 7.658 dcontainer: OK
> #0 8.626 ERROR: Feature "Pylint (via pipx)" (ghcr.io/devcontainers-contrib/features/pylint) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/pylint for help troubleshooting this error.
> ------
> [2023-03-14T02:46:55.217Z] ERROR: failed to solve: executor failed running [/bin/sh -c cp -ar /tmp/build-features-src/pylint_6 /tmp/build-features/  && chmod -R 0700 /tmp/build-features/pylint_6  && cd /tmp/build-features/pylint_6  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/build-features/pylint_6]: exit code: 127
> ```
> 
> Probably the standout is `exit code: 127`
> 
> Please redirect if this comment should become an issue or whateve.r

@dsturnbull Thanks man definitely sounds like an issue!😮 May I know which base image are you using for your devcontainer?  If you can provide the `devcontainer.json` you are using to replicate the problem it will be even more helpful!

**Comment by danielbraun89** [comment]
Hey @dsturnbull , could be related to #336 
Is there any chance you are running devcontainer on MacOS?

**Comment by feavilan04** [comment]
Hey @dsturnbull, same here:
` => ERROR [dev_containers_target_stage 4/9] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=bandit_1,target=/tmp/build-featu  34.1s
------
 > [dev_containers_target_stage 4/9] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=bandit_1,target=/tmp/build-features-src/bandit_1     cp -ar /tmp/build-features-src/bandit_1 /tmp/build-features/  && chmod -R 0700 /tmp/build-features/bandit_1  && cd /tmp/build-features/bandit_1  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/build-features/bandit_1:
#0 0.302 ===========================================================================
#0 0.302 Feature       : Bandit (via pipx)
#0 0.302 Description   : Bandit is a tool designed to find common security issues in Python code.
#0 0.302 Id            : ghcr.io/devcontainers-contrib/features/bandit
#0 0.302 Version       : 2.0.8
#0 0.302 Documentation : http://github.com/devcontainers-contrib/features/tree/main/src/bandit
#0 0.302 Options       :
#0 0.302     VERSION="latest"
#0 0.302 ===========================================================================
#0 32.52 dcontainer: OK
#0 34.11 ERROR: Feature "Bandit (via pipx)" (ghcr.io/devcontainers-contrib/features/bandit) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/bandit for help troubleshooting this error.
------
error: failed to solve: executor failed running [/bin/sh -c cp -ar /tmp/build-features-src/bandit_1 /tmp/build-features/  && chmod -R 0700 /tmp/build-features/bandit_1  && cd /tmp/build-features/bandit_1  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/build-features/bandit_1]: exit code: 127`

Using MacOS with apple silicon M1
