### ISSUE TITLE
Ansible version option is ignored

### ISSUE THREAD

**Issue by SheGe** [devcontainers-contrib/features#338]
Ansible feature has documented `version` option which is ignored.
By quick review of `dependencies.sh` file the version is not used by this module what result with `latest` version installed always.

**Comment by danielbraun89** [comment]
@SheGe Thanks for reporting!
Fixed in ansible ghcr.io/devcontainers-contrib/features/ansible:2.0.9
A version selection test also has been included: https://github.com/devcontainers-contrib/features/blob/bfeda7ea81f96d7ecaadc51163983221398859a8/test/ansible/test_version_selection.sh
