### ISSUE TITLE
BUG: Asdf plugins rewrites previous one

### ISSUE THREAD

**Issue by glagius** [devcontainers-contrib/features#340]
Hello guys!
When i tried to make my dev environment with devContainers, i've found that i can't use multiple asdf plugins selected by cli.
This is exemple:
```
"features": {
		"ghcr.io/devcontainers-contrib/features/asdf-package:1": {},
		"ghcr.io/devcontainers-contrib/features/grpcurl-asdf:2": {},
		"ghcr.io/jungaretti/features/make:1": {},
		"ghcr.io/balazs23/devcontainers-features/bazel:1": {},
		"ghcr.io/devcontainers-contrib/features/elixir-asdf:2": {},
		"ghcr.io/devcontainers-contrib/features/erlang-asdf:2": {}
	}
```
After images was build, there is only last one plugin exist.
However in console you can see that plugins installed one by one.

**Comment by danielbraun89** [comment]
Thanks @glagius looks like a major bug! 😮 Looking into it
