### ISSUE TITLE
HomeBrew-Package creates a .gitconfig file and thus breaks devcontainer copy of this file.

### ISSUE THREAD

**Issue by ross-p-smith** [devcontainers-contrib/features#346]
The homebrew-package feature which is used by a number of features in this repo adds a git safe directory (The following line can be seen in https://github.com/devcontainers-contrib/features/blob/main/src/homebrew-package/install.sh#L65

```bash
git config --global --add safe.directory "$(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core"
```

This means that when the devcontainer features finish installing the .gitconfig file is left. This then means that the host .gitconfig does not get copied into the devcontainer as it already exists - and thus breaking everyone's gitconfig.

You should change this to use the System config (.git/config) and not the users config (.gitconfig). See here for reference: - https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

**Comment by ross-p-smith** [comment]
Here is another example of the issue: - https://github.com/microsoft/vscode-remote-release/issues/7589

**Comment by danielbraun89** [comment]
@ross-p-smith thanks for finding this bug! I have changed to --system config as you suggested. 
(If this will not help ill simply delete the created .gitconfig  at the end of the installation)

**Comment by ross-p-smith** [comment]
Retested - all works perfectly - many thanks!
