### ISSUE TITLE
[Bug]:  /bin/bash: line 1: sudo: command not found

### ISSUE THREAD

**Issue by dloez** [devcontainers-contrib/features#382]
### Feature id and version

ghcr.io/devcontainers-contrib/features/ansible:2

### Devcontainer base Image

ubuntu:22.10

### What happened?

When building the devcontainer using the following devcontainer.json file, you get an error when the install.sh script is invoked as it tries to use the sudo command. According to the segment "[Invoking install.sh](https://containers.dev/implementors/features/#invoking-installsh)" of the official documentation of devcontainer features, sudo should not be required:
> The install.sh script for each Feature should be executed as root during a container image build. This allows the script to add needed OS dependencies or settings that could not otherwise be modified. This also allows the script to switch into another user’s context using the su command (e.g., su ${USERNAME} -c "command-goes-here"). In combination, this allows both root and non-root image modifications to occur even if sudo is not present in the base image for security reasons.

devcontainer.json:
```json
{
    "name": "admin-tools",
    "image": "ubuntu:22.10",

    "features": {
        "ghcr.io/devcontainers/features/python:1": {
            "version": "3.11.3",
            "installTools": false
        },
        "ghcr.io/devcontainers-contrib/features/ansible:2": {}
    }
}
```

### Relevant log output

```shell
> [dev_containers_target_stage 6/6] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=ansible_2,target=/tmp/build-features-src/ansible_2     cp -ar /tmp/build-features-src/ansible_2 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/ansible_2  && cd /tmp/dev-container-features/ansible_2  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/ansible_2:
#0 0.651 ===========================================================================
#0 0.651 Feature       : Ansible (via pipx)
[2023-04-19T12:06:51.902Z] 
#0 0.651 Description   : Ansible is a suite of software tools that enables infrastructure as code.
#0 0.651 Id            : ghcr.io/devcontainers-contrib/features/ansible
#0 0.651 Version       : 2.0.13
#0 0.651 Documentation : http://github.com/devcontainers-contrib/features/tree/main/src/ansible
#0 0.651 Options       :
#0 0.651     VERSION="latest"
#0 0.651 ===========================================================================
#0 0.656 bash: cannot set terminal process group (1): Inappropriate ioctl for device
#0 0.656 bash: no job control in this shell
#0 7.324 nanolayer
#0 14.73 cd /tmp/tmps15is8b8 && chmod +x -R . && sudo _REMOTE_USER="root" _REMOTE_USER_HOME="/root" PACKAGE="ansible-core" INJECTIONS="ansible" VERSION="latest" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-4dPowuPAxU/nanolayer" bash  -i  +H ./install.sh
#0 14.73 /bin/bash: line 1: sudo: command not found
```

**Comment by danielbraun89** [comment]
@dloez Thanks for finding and reporting this!

This is a serious problem, it went unnoticed because of the usage of microsoft containers as basis for the feature testing
(usage of  `mcr.microsoft.com/devcontainers/base:ubuntu`) which do contain `sudo` unlike bare ubuntu

I am working regenerated all features based on new installation logic which removes the `sudo` command

**Comment by danielbraun89** [comment]
version `ghcr.io/devcontainers-contrib/features/ansible:2.0.14`  should work correctly

**Comment by dloez** [comment]
Can confirm this is now working as intended. Thanks!
