### ISSUE TITLE
[Bug]: ZSH fails to install

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [devcontainers-contrib/features#417]
### Feature id and version

ghcr.io/devcontainers-contrib/features/zsh-plugins:0

### Devcontainer base Image

ubuntu:22.04

### What happened?

My dev container won't come up using the ZSH plugin. Before I begin, just want to say ❤️ thanks to this repo's maintainers! 😄 

# Steps to reproduce

devcontainer.json
```
{
	"name": "Existing Docker Compose (Extend)",
	"dockerComposeFile": [
		"docker-compose.yml"
	],
	"service": "pocketknife",
	"workspaceFolder": "/workspaces",
	"features": {
		"ghcr.io/devcontainers-contrib/features/zsh-plugins:0": {},
		"ghcr.io/devcontainers/features/aws-cli:1": {},
		"ghcr.io/devcontainers/features/git:1": {},
		"ghcr.io/devcontainers/features/node:1": {},
		"ghcr.io/mpriscella/features/sops:1": {},
		"ghcr.io/devcontainers-contrib/features/apt-get-packages:1": {},
		"ghcr.io/devcontainers-contrib/features/curl-apt-get:1": {},
		"ghcr.io/devcontainers-contrib/features/npm-package:1": {},
		"ghcr.io/devcontainers-contrib/features/pipenv:2": {},
		"ghcr.io/devcontainers-contrib/features/wget-apt-get:1": {},
		"ghcr.io/eitsupi/devcontainer-features/jq-likes:1": {},
		"ghcr.io/guiyomh/features/vim:0": {},
		"ghcr.io/jungaretti/features/make:1": {},
		"ghcr.io/devcontainers/features/java:1": {}
	}
}
```

docker-compose.yml
```
version: '3'
services:
  pocketknife:
    container_name: pocketknife_dev
    image: ubuntu:22.04
    network_mode: host
    volumes:
      - ..:/workspaces:cached
      - $HOME/.aws:/root/.aws
      - $HOME/.ssh:/root/.ssh
    restart: always
    command: sleep infinity
```

With these placed inside a `.devcontainer` directory from a project's root, opening the project via VSCode causes a failure with the attached logs.

# Question

One thing I don't understand is why the installer would expect anything to be at `/root/.zshrc`. Isn't the purpose of the plugin to install everything associated with ZSH? Maybe I'm misunderstanding the design though.

### Relevant log output

```shell
> [dev_containers_target_stage 13/31] RUN chmod -R 0755 /tmp/dev-container-features/zsh-plugins_1 && cd /tmp/dev-container-features/zsh-plugins_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh:
#0 0.262 ===========================================================================
#0 0.262 Feature       : ZSH Plugins
#0 0.262 Description   : Install (Oh-My-)ZSH plugins
#0 0.262 Id            : ghcr.io/devcontainers-contrib/features/zsh-plugins
#0 0.262 Version       : 0.0.2
#0 0.262 Documentation : http://github.com/devcontainers-contrib/features/tree/main/src/zsh-plugins
#0 0.262 Options       :
#0 0.262     PLUGINS=""
#0 0.262     OMZPLUGINS=""
#0 0.262     USERNAME=""
#0 0.262 ===========================================================================
#0 0.269 sed: can't read /root/.zshrc: No such file or directory
#0 0.270 ERROR: Feature "ZSH Plugins" (ghcr.io/devcontainers-contrib/features/zsh-plugins) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/zsh-plugins for help troubleshooting this error.
------
```

**Comment by danielbraun89** [comment]
@tyrannosaurus-becks  thanks for reporting!
Seems like the original intend for this feature is just installing plugins for an already installed zsh. therefor the scripts assumed zsh already installed and configuration is there. The script also assumed an image with git and ca-certificates already installed, which is not the case with plain ubuntu. 

I have added a logic which install zsh if it does not exists and create the configuration file is created if is not exists.
I have also added a test to check clean ubuntu image

Please try latest version : `ghcr.io/devcontainers-contrib/features/zsh-plugins:0.0.4`

**Comment by tyrannosaurus-becks** [comment]
That is awesome! Thanks @danielbraun89 !!!!
