### ISSUE TITLE
[Bug]: kubectx/kubens Installing Old Versions

### ISSUE THREAD

**Issue by natescherer** [devcontainers-contrib/features#459]
### Feature id and version

ghcr.io/devcontainers-contrib/features/kubectx-kubens:1.0.2

### What happened?

Hello! So I'm not sure if this is technically a bug or just your intended behavior, but, due to a peculiarity in how kubectx/kubens does releases, this isn't actually installing the latest version of the programs that are written in Go, but the older, bash script versions.

Took me a while to figure out, but if you ACTUALLY want a version of kubectx/kubens newer than 0.8.0, you need to pull down the binaries from the releases, not the files names kubectx/kubens on the releases.

Are you intending to only offer the bash-based versions of these utilities, or would you be open to a PR to add support for the Go versions?

**Comment by danielbraun89** [comment]
thanks @natescherer ! this is actually a bug and not my intended behavior, looking into it

**Comment by natescherer** [comment]
I created #499 to fix this bug.
