### ISSUE TITLE
[Feature Request]: Can you add support for txs support for Typescript

### ISSUE THREAD

**Issue by mdabir1203** [devcontainers-contrib/features#461]
### Requested Feature

It could be done in similar way like below. Or if you have any guidelines we can do this

// devcontainer.json
{
  "name": "TypeScript Devcontainer",
  "image": "your-custom-devcontainer-image",
  "extensions": [
    "dbaeumer.vscode-eslint"
  ],
  "features": {
    "ghcr.io/devcontainers-contrib/features/tsx:1": {
      "version": "latest",
      "clientOnly": "true"
    }
  }
}

In this configuration, the ghcr.io/devcontainers-contrib/features/tsx:1 feature is specified to install TypeScript. By setting "clientOnly": "true", only the TypeScript client and related tools will be installed, without the full TypeScript server.

**Comment by danielbraun89** [comment]
@mdabir1203  thanks for the suggestion!
added both `tsx` and `ts-node` features  (`ghcr.io/devcontainers-contrib/features/tsx:1` and `ghcr.io/devcontainers-contrib/features/ts-node:1`

I hope I unserstood the client-only flag correctly, so currently I opted to is not installing typescript by default and if wanted,  it needs to be manually installed (or by using its designated feature)

**Comment by mdabir1203** [comment]
Thanks a ton :)
