### ISSUE TITLE
[Bug]: Typo in comments for clean_download

### ISSUE THREAD

**Issue by tomharvey** [devcontainers-contrib/features#487]
### Feature id and version

Lots of them

### What happened?

There is a minor typo in the clean_install comments:

> minimal impact on contaier layer size

instead of

> minimal impact on container layer size

**Comment by tomharvey** [comment]
Fix in https://github.com/devcontainers-contrib/features/pull/488

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned https://github.com/devcontainers-contrib/features/issues/628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451. There is a fork that is being worked on to update and maintain the features https://github.com/devcontainers-extra/features

**Comment by tomharvey** [comment]
Thanks @evilhamsterman  for the heads up and the work to tidy things a bit for the community. 👍🏻
