### ISSUE TITLE
LLVM install feature

### ISSUE THREAD

**Issue by 0xMihir** [devcontainers-contrib/features#490]
### Requested Feature

This would entail a simple wrapper around the LLVM installer script (https://apt.llvm.org/llvm.sh), allowing users to specify the version or just install the latest LLVM

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned https://github.com/devcontainers-contrib/features/issues/628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451. There is a fork that is being worked on to update and maintain the features https://github.com/devcontainers-extra/features

**Comment by 0xMihir** [comment]
Ah, that's unfortunate.
