### ISSUE TITLE
PDFTOPPM: Add poppler-utils

### ISSUE THREAD

**Issue by Azel-ytof** [devcontainers-contrib/features#505]
### Requested Feature

Hi,

I have some projects wich use pdftoppm (from poppler-utils apt package).
So it could be a great thing to test scripts in local before run it on server.
But I am not sure if I can do a good contribution (I will try if I have some time but not now...)

So if someone could do this, I will thank her/him a lot ! :D
Else see you in few months... ^^'

Thanks !

**Comment by danielbraun89** [comment]
@Azel-ytof  Thanks for the suggestion! The feature has been added, and can be used in the following way:

```
"features": {
    "ghcr.io/devcontainers-contrib/features/poppler-utils-apt-get:latest": {}
}
```

**Comment by Azel-ytof** [comment]
Thank you a lot @danielbraun89 ! 😄
