### ISSUE TITLE
epinio-cli

### ISSUE THREAD

**Issue by gitricko** [devcontainers-contrib/features#522]
### Requested Feature

Like heruku-cli, i would like to see epinio-cli

https://docs.epinio.io/installation/install_epinio_cli

**Comment by danielbraun89** [comment]
@gitricko Thanks for the suggestion! The feature has been added, and can be used in the following way:

```
"features": {
    "ghcr.io/devcontainers-contrib/features/epinio:1.0.0": {}
}
```
