### ISSUE TITLE
[Feature Request]: Gleam CLI

### ISSUE THREAD

**Issue by NicoVIII** [devcontainers-contrib/features#535]
### Requested Feature

Hi everyone!

I think it would be cool to be able to install the Gleam CLI as a devcontainers feature as well. The recommended way to do this is via GitHub Releases according to https://gleam.run/getting-started/installing/#installing-gleam.

The repository is found here: https://github.com/gleam-lang/gleam/releases

There are already things which are installed via GitHub Releases as far as I know, therefore I hope this is quite easy to do. If I find the time I will look into this as well to see, how this works here exactly :)

Thanks for your work!

**Comment by danielbraun89** [comment]
@NicoVIII Thanks for the suggestion! The feature has been added, and can be used in the following way:
```
"features": {
    "ghcr.io/devcontainers-contrib/features/gleam:1.0.0": {}
}
```

**Comment by NicoVIII** [comment]
Thanks, really cool! 🥰
