### ISSUE TITLE
[Bug]: Zsh-Plugin Feature Questions/Options Aren't Asked Properly

### ISSUE THREAD

**Issue by RadhiRasho** [devcontainers-contrib/features#556]
### Feature id and version

ghcr.io/devcontainers-contrib/features/zsh-plugins:0

### Devcontainer base Image

mcr.microsoft.com/devcontainers/base:ubuntu

### What happened?

I'm not fully certain that this is a bug or an intended, but I noticed that the two questions/options that should appear for Plugins and OMZ Plugins don't get asked/allow configuration during initial setup for the Dev Container don't get asked for Zsh Plugins. 

### Relevant log output

```shell
No Log Out put, issue is before logging.
```

**Comment by RadhiRasho** [comment]
The feature in question also seems to setup the `plugins` and `omzplugins` only when the username used is `vscode` and even then you have to finish building your dev container and then make the changes in the `devcontainer.json` file and rebuild for the plugins to be plugged in place

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned https://github.com/devcontainers-contrib/features/issues/628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451. There is a fork that is being worked on to update and maintain the features https://github.com/devcontainers-extra/features

**Comment by RadhiRasho** [comment]
Thank you, I'll close this out
