### ISSUE TITLE
[Bug]: Tea cli has been renamed to pkgx

### ISSUE THREAD

**Issue by char8x** [devcontainers-contrib/features#571]
### Feature id and version

ghcr.io/devcontainers-contrib/features/tea:1

### What happened?

When installing binary through tea, it will prompt that it cannot be executed because `pkgx` cannot be found.

```sh
❯ tea install node
pkgx: installed: ~/.local/bin/node

❯ node --version
/home/vscode/.local/bin/node: 3: exec: pkgx: not found
```

### Relevant log output

```shell
❯ tea --help
usage:
  pkgx [+pkg@x.y…] <program|path> [--] [arg…]

examples:
  $ pkgx node@18 --eval 'console.log("pkgx.sh")'
  $ pkgx +openssl cargo build
  $ pkgx@latest npx@latest cowsay@latest 'fancy a cuppa?'
  $ env +bun   # https://docs.pkgx.sh/shell-integration

more:
  $ pkgx --help --verbose
  $ open https://docs.pkgx.sh


❯ cat ~/.local/bin/node
#!/bin/sh
if [ "$PKGX_UNINSTALL" != 1 ]; then
  exec pkgx +nodejs.org -- node "$@"
else
  cd "$(dirname "$0")"
  rm node && echo "uninstalled: nodejs.org" >&2
fi
```

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned https://github.com/devcontainers-contrib/features/issues/628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451. There is a fork that is being worked on to update and maintain the features https://github.com/devcontainers-extra/features
