### ISSUE TITLE
[Feature Request]: zsh-plugins - Add GitHub alias support

### ISSUE THREAD

**Issue by nandordudas** [devcontainers-contrib/features#590]
### Requested Feature

# 💡 I have an idea

Add [insteadOf] git configuration for shorter GitHub based plugin URLs.

```bash
git config url."https://github.com/".insteadOf gh:
```

After that change the base could replaced from `https://github.com/` to `gh:` in the `devcontainer.json` file.

```diff
{
  "features": {
    "ghcr.io/devcontainers-contrib/features/zsh-plugins:0": {
-     "omzPlugins": "https://github.com/z-shell/F-Sy-H https://github.com/zsh-users/zsh-autosuggestions",
+     "omzPlugins": "gh:z-shell/F-Sy-H gh:zsh-users/zsh-autosuggestions",
      "plugins": "F-Sy-H zsh-autosuggestions"
    }
  }
}
```

Corresponding file: https://github.com/devcontainers-contrib/features/blob/main/src/zsh-plugins/install.sh

[insteadOf]: https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned https://github.com/devcontainers-contrib/features/issues/628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451. There is a fork that is being worked on to update and maintain the features https://github.com/devcontainers-extra/features

**Comment by nandordudas** [comment]
Thanks for the info 🙇‍♂️
