### ISSUE TITLE
[Bug]: [syncthing]: command not found

### ISSUE THREAD

**Issue by MambaWong** [devcontainers-contrib/features#605]
### Feature id and version

ghcr.io/devcontainers-contrib/features/syncthing:1

### Devcontainer base Image

mcr.microsoft.com/devcontainers/base:ubuntu-22.04

### What happened?

run syncthing

### Relevant log output

```shell
/usr/local/bin/syncthing: line 1: [syncthing]: command not found
/usr/local/bin/syncthing: line 3: file: command not found
/usr/local/bin/syncthing: line 4: 21027/udp: No such file or directory
/usr/local/bin/syncthing: line 6: [syncthing-gui]: command not found
/usr/local/bin/syncthing: line 8: web: command not found
```

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned https://github.com/devcontainers-contrib/features/issues/628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451. There is a fork that is being worked on to update and maintain the features https://github.com/devcontainers-extra/features

**Comment by MambaWong** [comment]
thanks
