### ISSUE TITLE
[Bug]: Pre-existing nanolayers of the same version are always skipped

### ISSUE THREAD

**Issue by norseto** [devcontainers-contrib/features#637]
### Feature id and version

ghcr.io/devcontainers-contrib/features/istioctl:1

### Devcontainer base Image

mcr.microsoft.com/devcontainers/base:bullseye

### What happened?

In install.sh, ensure nanolayer version.
```
ensure_nanolayer nanolayer_location "v0.5.4"
```
In library_scripts.sh, it seems to compare specified version and nanolayer version.
```python
        # make sure its of the required version
        if ! [ -z "${__nanolayer_location}" ]; then
            local current_version
            current_version=$($__nanolayer_location --version)


            if ! [ $current_version == $required_version ]; then
                echo "skipping usage of pre-existing nanolayer. (required version $required_version does not match existing version $current_version)"
                __nanolayer_location=""
            fi
        fi
```
However, doesn't `nanolayer --version` always return the version without the initial v?
If a nanolayer exists, it seems to always skip the existing nanolayer even if the versions match.

### Relevant log output

```shell
[22:38:19] info #11 31.47 Found a pre-existing nanolayer which were given in env variable: /tmp/nanolayer-goNK3pxScv/nanolayer
[22:38:19] info #11 31.59 skipping usage of pre-existing nanolayer. (required version v0.5.4 does not match existing version 0.5.4)
```

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned #628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451

**Comment by norseto** [comment]
Thanks, closing issue...
