### ISSUE TITLE
Fix GitHub Actions warnings

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/features#71]
There are a lot of these:

![image](https://user-images.githubusercontent.com/61068799/203235568-12a20c81-49e6-450b-8d67-294edc3e3a6c.png)

~~TODO: Add suggestions to fix here @jcbhmr~~

Here's what causes these warnings and how to solve them:
- [x] Please update the following actions to use Node.js 16: actions/checkout@v2
- [x] The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ (this refers to the `find-features` action that uses `set-output` stuff)

That's it! There are so many errors with the same message since the same action is being run in a matrix (and thus the same actions/checkout@v2 is triggering warnings a lot).

**Comment by danielbraun89** [comment]
fixed in #93 
migrated all checkout actions to v3 (node 16 based) 
also replaced set_output usage in feature discovery action to set env
