### ISSUE TITLE
Change repo description to reflect new readme

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/features#78]
I humbly suggest that one of the admins with the power to do change the repository's "Description" field from "Contributions are Welcomed!" to "🐳 Extra add-in features for Devcontainers and GitHub Codespaces". This description field is sort of the "title" for Google search results. I think it would be wise to make it a more substantive description.

![image](https://user-images.githubusercontent.com/61068799/203651289-40077e88-8b7f-4b07-9076-d45e0bcd9996.png)

I personally try to keep the repo-level Description field the same as the tag-line-ish thing that I always put under the `<h1>` in the readme.

<details>
  <summary>Example from one of my repos</summary>

![image](https://user-images.githubusercontent.com/61068799/203651492-17e7f23a-7276-4ae9-967a-160bdfaf2310.png)
![image](https://user-images.githubusercontent.com/61068799/203651506-56f75543-bca3-4d1e-9c8b-5b69bd0221ec.png)
![image](https://user-images.githubusercontent.com/61068799/203704948-e2579a59-fa1b-4766-b3ed-23f0c899fe89.png)

</details>

_Originally posted by @jcbhmr in https://github.com/devcontainers-contrib/features/issues/69#issuecomment-1325697184_

**Comment by danielbraun89** [comment]
done 😃
