### ISSUE TITLE
localstack failing build Action

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/features#82]
Right now [the localstack feature is failing its tests (as of the latest commit at time of writing)](https://github.com/devcontainers-contrib/features/actions/runs/3535267919/jobs/5933837746).

<details>
  <summary>Image of the failed Action</summary>

![image](https://user-images.githubusercontent.com/61068799/204057596-d3a1384e-107d-4fbb-a07b-c94602fb633e.png)

![image](https://user-images.githubusercontent.com/61068799/204057586-7280457f-7707-471c-bd2e-0123bd82a83a.png)

</details>

The error message that kills the build process is:

```
AttributeError: module 'distutils.log' has no attribute 'warning'. Did you mean: 'warnings'?
```

[Link to it in the Actions log](https://github.com/devcontainers-contrib/features/actions/runs/3535267919/jobs/5933837746#step:4:1422)

The most relevant result from Google seems to be: https://github.com/pypa/setuptools/issues/3707. Here's the PR that supposedly fixes the issue: https://github.com/pypa/setuptools/pull/3709. I don't know what the fix would be. Maybe this is just some issue upstream that will eventually go away?

**Comment by danielbraun89** [comment]
Thanks for finding this 

This seems to be solved in the very recent setuptools 65-6-3  (see changelog https://setuptools.pypa.io/en/latest/history.html#v65-6-3 )
So this might get solved in newly created pipx environment without any changes to the current scripts

However... currently scripts will rely on a preinstalled pipx (if exists ) - thus inheriting any old setuptools already in existence in the pipx shared bin folder 
I believe the proper solution for this and many future errors that can occur, is to force latest version for setuptools (and also for pip and wheel for good measure)  even when using a preexisting pipx 
working on a PR

**Comment by jcbhmr** [comment]
Awesome! 👍
