### ISSUE TITLE
Haskell available only for root

### ISSUE THREAD

**Issue by danielbraun89** [devcontainers-contrib/features#85]
started this issue for the @DaneWeber  PR #74

**Comment by DaneWeber** [comment]
Happy to see PR #74 merged. I'm looking forward to @jcbhmr's PR applying a better pattern than monkeying with `$HOME`.

@danielbraun89 -- I believe we still need the version bump. Would you like me to open a PR for that?

Are we attempting semantic versioning with these Features? I doubt it's a big deal, but I'd actually argue that this is a breaking change. _If_ folks have been using the previous version successfully, they're either running as root or doing something else to make it work, and there's a good chance that the absence of the programs in `/root` will cause their setup to fail.

**Comment by danielbraun89** [comment]
already  bumped in eadbf443d8634556166770cfb420d683f70b5f12 👍
